### ISSUE TITLE
What password for the MySQL root user?

### ISSUE THREAD

**Issue by steveharman** [mesadhan/processmaker-docker#1]
In the ReadMe there are two "Step 4" screenshots:

- The first "Step 4" screenshot shows a blank field for the MySQL root user's password, along with the error I get in red text and an explanation of how to retrieve the MySQL container's IP address.
- The second  "Step 4" screenshot magically seems to have something entered in the root user's password field which wasn't present on the first screen.  

Sadly that same magic doesn't happen for me and I can't find any reference to the password I should be using for the MySQL root user.   

Does anyone have any ideas?

Thanks

![process](https://user-images.githubusercontent.com/12557929/79205102-69b41f00-7e35-11ea-8995-4b0c5e29c10a.png)

**Comment by mesadhan** [comment]
No Problem, It's default password is `PM-DBPassw0rd`. You can change it from below docker-compose-ce.yml file

- https://github.com/mesadhan/processmaker-docker/blob/master/docker-compose-ce.yml

Thanks!
